#!/bin/bash
 
# Function to choose between YAY and Paru for installation
choose_yay_or_paru() {
    printf "Choose AUR Helper: YAY or Paru\n"
    read -p "Enter 'y' for YAY or 'p' for Paru: " aur_helper

    # Validate user input for AUR helper selection
    while [[ ! "$aur_helper" =~ ^[yp]$ ]]; do
        read -p "Invalid input. Please enter 'y' for YAY or 'p' for Paru: " aur_helper
    done

    if [[ "$aur_helper" == "y" ]]; then
        install_yay
    elif [[ "$aur_helper" == "p" ]]; then
        install_paru
    fi

    ask_install_aur_programs
}

# Function to prompt user for installing AUR programs
ask_install_aur_programs() {
    read -p "Do you want to install AUR programs? (y/n): " install_aur
    if [[ "$install_aur" == "y" ]]; then
        install_aur_packages
    else
        printf "Skipping AUR programs installation.\n"
    fi
}

# Function to install YAY
install_yay() {
    printf "Installing YAY... "
    if [ -d "yay" ]; then
        rm -rf yay
    fi

    git clone https://aur.archlinux.org/yay.git
    cd yay || { echo "Error: Unable to change directory to yay. Exiting."; exit 1; }
    
    if ! makepkg -si --needed --noconfirm; then
        echo "Error: Failed to install YAY. Exiting."
        exit 1
    fi

    cd ..
    rm -rf yay
    printf "YAY installed successfully.\n"
}

# Function to install Paru
install_paru() {
    printf "Installing Paru... "
    if [ -d "paru" ]; then
        rm -rf paru
    fi

    git clone https://aur.archlinux.org/paru.git
    cd paru || { echo "Error: Unable to change directory to paru. Exiting."; exit 1; }
    
    if ! makepkg -si --needed --noconfirm; then
        echo "Error: Failed to install Paru. Exiting."
        exit 1
    fi

    cd ..
    rm -rf paru
    printf "Paru installed successfully.\n"
}

# Function to install AUR packages
install_aur_packages() {
    printf "Installing AUR Packages... "
    if [[ "$aur_helper" == "p" ]]; then
        paru -S --needed --noconfirm "${yay_programs[@]}"
    else
        yay -S --needed --noconfirm "${yay_programs[@]}"
    fi
    printf "AUR Packages installed successfully.\n"
}

# Main script

# Programs to install using yay
yay_programs=(
    brave-bin
    dropbox
    spotify
    stremio
    teamviewer
    # Add or remove AUR programs as needed
)

# Run function
choose_yay_or_paru
ask_install_aur_programs